### PR TITLE
Move files from tmp dir to avoid deletion during tmp dir cleanup

### PR DESCRIPTION
**Pull request by tthyer**
*Issue #, if available:*
https://github.com/aws-samples/aws-genomics-workflows/issues/118

*Description of changes:*
I have moved all the files set up by `cromwell-resources.template.yaml` stored in `/tmp` to `/home/ec2-user`. This is a proposal to start a conversation -- I don't believe the home directory is necessarily the best place, but I do recommend moving all files that should persist out of `/tmp`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by wleepang** [comment]
Which files are useful for a user shelling into the cromwell server instance to access? If what is needed is a place that won't get vacuumed up routinely, would a directory in `/opt` work?

**Comment by tthyer** [comment]
In addition to log files the users might want to see, there's the supervisor sock and pid files, and where the conf files should go. 
A few suggestions follow -- I'm basing this on where supervisor [says](http://supervisord.org/configuration.html) it looks for the conf file, and where sock files and log files are typically found:
/etc/supervisor/supervisord.conf
/etc/supervisor/supervisord.pid or /var/run/supervisord.pid
/var/run/supervisor.sock
/var/log/supervisord.log
/var/log/cromwell-server.log

**Comment by wleepang** [comment]
`*.log` files are ok to keep in `/home/ec2-user/`. Other operational files like `supervisor.{pid,sock}` probably should go somewhere a bit more out of the way like `/opt` or `/var/run` so that there is less likelihood of accidental modification or deletion.

**Review by wleepang — APPROVED** [review]
Overall, I think this is fine. If cases arise where these files get poked at unnecessarily, we can update accordingly then.

**Pull request merged**
